### ISSUE TITLE
Spams the console when switchin Not Enough Enchants With So Many Enchants

### ISSUE THREAD

**Issue by ghost** [Charles445/RLTweaker#2]
This is what it spams
[02:54:01] [Server thread/ERROR] [RLTweaker]: Error in CurseOfPossession onExist Invoke
java.lang.IllegalArgumentException: java.lang.ClassCastException@1518373e
        at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at com.charles445.rltweaker.handler.SMEHandler$CurseOfPossession.onExist(SMEHandler.java:228) [SMEHandler$CurseOfPossession.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1616_CurseOfPossession_onExist_WorldTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:776) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

The @ value changes every time it spams which is like every second

**Comment by Charles445** [comment]
That's weird, which one of the two mods are you using, Not Enough Enchantments or So Many Enchantments?
Which version of the enchantments mod are you using?

(if you want to quickly hide this error, you can go into the rltweaker mod config and set "Manage Curse of Possession" to false)

**Comment by ghost** [comment]
Im using the latest 1.12.2 version of So Many Enchantments as Not Enough Enchantments Were Incompatible With Silent Gear

**Comment by ghost** [comment]
I might use your fork of the mod to see if that works

**Comment by Charles445** [comment]
I'm maintaining So Many Enchantments right now so the fork is also up on curseforge, just set as a beta version for now until it gets tested a bit more.
https://www.curseforge.com/minecraft/mc-mods/so-many-enchantments/files/2999005 quick link if you want it

This has all of the fixes from RLTweaker built in, so you can completely disable RLTweaker's somanyenchantments support in its config if you're using So Many Enchantments 0.5.0

**Comment by Charles445** [comment]
Oh I should also mention, if you update somanyenchantments you should delete the old somanyenchantments config, the new config is pretty different.

**Comment by ghost** [comment]
Yeah i figured as i noticed your fork of it in your repo. 
It worked out

**Comment by Charles445** [comment]
Cool, let me know if anything else goes wrong
