### ISSUE TITLE
Transformer Anomalies

### ISSUE THREAD

**Issue by Charles445** [Charles445/RLTweaker#3]
Ran into a couple of bizarre issues, these issues are inconsistent and random, the worst kind of issue...

All of these issues appeared with sorting index 1001, and only happened once each.

```
[22:36:26] [main/INFO] [STDOUT]: [com.charles445.rltweaker.asm.RLTweakerASM:transform:64]: Failed at patch Less Collisions
[22:36:26] [main/INFO] [STDOUT]: [com.charles445.rltweaker.asm.RLTweakerASM:transform:65]: Failed to write net.minecraft.world.World
[22:36:26] [main/INFO] [STDERR]: [com.charles445.rltweaker.asm.RLTweakerASM:transform:66]: java.lang.RuntimeException: Couldn't find getEntitiesWithinAABBExcludingEntity or func_72839_b
```
This one meant that it successfully found the correct getCollisionBoxes method, but for some reason it was unable to find the function call to func_72839_b or getEntitiesWithinAABBExcludingEntity .
Where did it go? And why only this once?
Surely it wasn't notch named, the transformer is sorted past 1000...
Perhaps a separate patch conflicted with it, and the load order messing up that bad is simply a rare occurrence. That could be it.
I will probably rewrite this patch to avoid the World class entirely, all the core mods pile on it enough...

Here's another one-time problem

```
[21:30:55] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: com/charles445/rltweaker/util/WorldRadiusUtil
	at com.charles445.rltweaker.hook.HookWorld.getEntitiesWithinAABBExcludingEntity(HookWorld.java:22) ~[HookWorld.class:?]
	at net.minecraft.world.World.func_184144_a(World.java:1366) ~[amu.class:?]

... blah blah blah 

Caused by: java.lang.ClassNotFoundException: com.charles445.rltweaker.util.WorldRadiusUtil
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at com.charles445.rltweaker.hook.HookWorld.getEntitiesWithinAABBExcludingEntity(HookWorld.java:22) ~[HookWorld.class:?]
```

This one also only happened once. It crashed my dedicated server with a client connected to it.
This just SCREAMS rogue ClassLoader loading classes it shouldn't, it really does, but I can't imagine how. I had some unused imports earlier, but I don't think that'd do anything.

For safety, I'm running it all on 1002 and I turned WorldRadiusUtil into an instance based class. Imports are cleaned up too. That's all I got, honestly. I'll need some help with this one if the problems continue to show up.

**Comment by Charles445** [comment]
Looks like DynamicSurroundings ran into similar trouble. It ended up adding notch names first and switched to mixin later.
I might go ahead and add notch names to everything, wouldn't hurt.

**Comment by Charles445** [comment]
This may simply have been caused by random computer issues, and/or multiple copies of the game running at once.
I ran into an anomaly where a different mods' jar was not recognized as a mod, which was quite unexpected.
I'm going to chalk these up to random occurrences for now. Will leave this open in case someone runs into similar trouble in the future.
